---
server:
  port: 7072

spring:
  datasource:
    url: jdbc:postgresql://localhost/easy-news-feed
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: public
  servlet:
    multipart:
      max-request-size: 10GB
      max-file-size: 10GB